services:
  db:
    image: postgres:16-alpine
    container_name: yordan_upskill_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER} -d $${DB_DATABASE}"]
      interval: 5s
      retries: 5
    restart: unless-stopped

volumes:
  db-data:
    name: yordan_upskill_db_data 